version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    restart: unless-stopped

  node:
    labels:
      caddy: ${NODE_DOMAIN:-localhost}
      caddy.reverse_proxy: "{{upstreams 9944}}"
    image: zhenxunge-node
    networks:
      - caddy
    ports:
      - "9944:9944"
    volumes:
      - zhenxunge-node-data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  zhenxunge-node-data:
  caddy-data:
