version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - zhenxunge-node
    ports:
      - "9944:9944"
    volumes:
      - zhenxunge-node-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10

networks:
  zhenxunge-node:

volumes:
  zhenxunge-node-data:
